/* This program performs push and pop operations on a Stack using a Linked List */
#include <stdio.h>
#include <stdlib.h>
#include<conio.h>
struct node
{
    int info;
    struct node *ptr;
}*top,*top1,*temp;

void push(int data);
void pop();
void display();
void create();

void main()
{
    int no, ch;
    printf("\n1.Push");
    printf("\n2.Pop");
    printf("\n3.Display");
    printf("\n4.Exit");
    create();
    while (1)
    {
	printf("\nEnter your choice: ");
	scanf("%d", &ch);
	switch (ch)
	{
	case 1:
	    printf("Enter data: ");
	    scanf("%d", &no);
	    push(no);
	    break;
	case 2:
	    pop();
	    break;
	case 3:
	    display();
	    break;
	case 4:
	    exit(0);
	default :
	    printf("\nWRONG CHOICE");
	    break;
	}
    }
}

void create()
{
    top = NULL;
}

void push(int data)
{
    if (top == NULL)
    {
	top =(struct node *)malloc(1*sizeof(struct node));
	top->ptr = NULL;
	top->info = data;
    }
    else
    {
	temp =(struct node *)malloc(1*sizeof(struct node));
	temp->ptr = top;
	temp->info = data;
	top = temp;
    }
}

void display()
{
    top1 = top;

    if (top1 == NULL)
    {
	printf("Stack is empty");
	return;
    }

    while (top1 != NULL)
    {
	printf("%d ", top1->info);
	top1 = top1->ptr;
    }
}

void pop()
{
    top1 = top;

    if (top1 == NULL)
    {
	printf("\n Error : Trying to pop from empty stack");
	return;
    }
    else
	top1 = top1->ptr;
    printf("\n Popped value : %d", top->info);
    free(top);
    top = top1;
}
